{% set name = "nordic" %}
{% set ucname = "NORDic" %}
{% set version = "2.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: "https://github.com/sysbio-curie/MaBoSS-env-2.0/archive/refs/heads/master.tar.gz"
    sha256: a19dedced0739265042c73227793475c4c31a168717fb17c47c9361211b114ab
    folder: "MaBoSS-2.0"
  - url: "https://files.pythonhosted.org/packages/aa/d3/21009d1d34e8cb7022b9f357a96b066220898f331476f2eadb5e68926ad8/mpbn-4.2.tar.gz"
    sha256: fdba6e9dd8021f3c67c9668ce244a9f13ec6ea9dcd43e7dacc89e85a628eb76e
    folder: "mpbn-4.2"
  - url: "https://files.pythonhosted.org/packages/74/8c/60bbfe6b2083c47e8cf4c61296347234d707c443a1f001a81a6671420527/bonesis-0.6.8.1.tar.gz"
    sha256: b349beb0611da24b3a8dc95f342824af0bef13cedf68e9d90ce1fdda828405e4
    folder: "bonesis-0.6.8.1"
  - url: "https://files.pythonhosted.org/packages/25/2b/a1a63c04060cb70525fdece8a5961d9c8b393c2c5410ca18406cfea13342/{{ name }}-{{ version }}.tar.gz"
    sha256: 47008e4bef379a8c91915027300b44f88f087a7e3a8e900730e14b64876a9f8c
    folder: "{{ ucname }}-{{ version }}"
    
build:
  number: 0
  skip: True  # [py < 38]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - flex
    - bison
    - make
  host:
    - python
    - pip
    - clingo >=5.6.1
    - cmappy >=4.0.1
    - graphviz >=0.20.1
    - matplotlib-base
    - omnipath
    - openpyxl >=3.0.10
    - qnorm >=0.5.1
    - quadprog >=0.1.11
    - scikit-learn >=1.1.2
    - scipy >=1.6.2
    - seaborn >=0.12.1
    - tqdm >=4.62.3
    - numpy >=1.22.4,!=2.0.*,!=2.1.*
  run:
    - python
    - clingo >=5.6.1
    - cmappy >=4.0.1
    - graphviz >=0.20.1
    - matplotlib-base
    - omnipath
    - openpyxl >=3.0.10
    - qnorm >=0.5.1
    - quadprog >=0.1.11
    - scikit-learn >=1.1.2
    - scipy >=1.6.2
    - seaborn >=0.12.1
    - tqdm >=4.62.3
    - numpy >=1.22.4,!=2.0.*,!=2.1.*

test:
  imports:
    - NORDic
    - NORDic.NORDic_DR
    - NORDic.NORDic_DS
    - NORDic.NORDic_NI
    - NORDic.NORDic_PMR
    - NORDic.UTILS

about:
  home: "https://github.com/clreda/NORDic"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "NORDic: a Network-Oriented package for the Repurposing of Drugs"
  doc_url: "https://github.com/clreda/NORDic/blob/main/README.md"
  dev_url: "https://github.com/clreda/NORDic"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - clreda
  identifiers:
    - doi:10.5281/zenodo.7239047
{% set name = "nordic" %}
{% set ucname = "NORDic" %}
{% set version = "2.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: "https://github.com/sysbio-curie/MaBoSS-env-2.0/archive/refs/heads/master.tar.gz"
    sha256: a19dedced0739265042c73227793475c4c31a168717fb17c47c9361211b114ab
    folder: "MaBoSS-2.0"
  - url: "https://files.pythonhosted.org/packages/aa/d3/21009d1d34e8cb7022b9f357a96b066220898f331476f2eadb5e68926ad8/mpbn-4.2.tar.gz"
    sha256: fdba6e9dd8021f3c67c9668ce244a9f13ec6ea9dcd43e7dacc89e85a628eb76e
    folder: "mpbn-4.2"
  - url: "https://files.pythonhosted.org/packages/74/8c/60bbfe6b2083c47e8cf4c61296347234d707c443a1f001a81a6671420527/bonesis-0.6.8.1.tar.gz"
    sha256: b349beb0611da24b3a8dc95f342824af0bef13cedf68e9d90ce1fdda828405e4
    folder: "bonesis-0.6.8.1"
  - url: "https://files.pythonhosted.org/packages/25/2b/a1a63c04060cb70525fdece8a5961d9c8b393c2c5410ca18406cfea13342/{{ name }}-{{ version }}.tar.gz"
    sha256: 47008e4bef379a8c91915027300b44f88f087a7e3a8e900730e14b64876a9f8c
    folder: "{{ ucname }}-{{ version }}"
    
build:
  number: 0
  skip: True  # [py < 38]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - flex
    - bison
    - make
  host:
    - python
    - pip
    - clingo >=5.6.1
    - cmappy >=4.0.1
    - graphviz >=0.20.1
    - matplotlib-base
    - omnipath
    - openpyxl >=3.0.10
    - qnorm >=0.5.1
    - quadprog >=0.1.11
    - scikit-learn >=1.1.2
    - scipy >=1.6.2
    - seaborn >=0.12.1
    - tqdm >=4.62.3
    - numpy >=1.22.4,!=2.0.*,!=2.1.*
  run:
    - python
    - clingo >=5.6.1
    - cmappy >=4.0.1
    - graphviz >=0.20.1
    - matplotlib-base
    - omnipath
    - openpyxl >=3.0.10
    - qnorm >=0.5.1
    - quadprog >=0.1.11
    - scikit-learn >=1.1.2
    - scipy >=1.6.2
    - seaborn >=0.12.1
    - tqdm >=4.62.3
    - numpy >=1.22.4,!=2.0.*,!=2.1.*

test:
  imports:
    - NORDic
    - NORDic.NORDic_DR
    - NORDic.NORDic_DS
    - NORDic.NORDic_NI
    - NORDic.NORDic_PMR
    - NORDic.UTILS

about:
  home: "https://github.com/clreda/NORDic"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "NORDic: a Network-Oriented package for the Repurposing of Drugs"
  doc_url: "https://github.com/clreda/NORDic/blob/main/README.md"
  dev_url: "https://github.com/clreda/NORDic"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - clreda
  identifiers:
    - doi:10.5281/zenodo.7239047
