on:
  release:
    types: [published]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Generation of NORDic paper draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: NORDic
          path: paper/paper.pdf
