name: NORDic documentation

on: [push]
#on:
#  release:
#    types: [published]

jobs:
  docs:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} using Miniconda
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and build NORDic
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r pip/requirements.txt
          python -m pip install .
          python -m pip install sphinx sphinx-gallery Pillow sphinx-rtd-theme
      - name: Sphinx build
        run: |
          sphinx-apidoc -f -o docs/ src/NORDic --implicit-namespace
          sphinx-build docs _build
      - name: Deploy documentations
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
