name: NORDic post-pushing testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} using Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          use-mamba: true
          mamba-version: "*"
          channels: colomoto
      - name: Set up Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install dependencies and build NORDic
        shell: bash -l {0}
        run: |
          mamba init
          mamba activate test
          mamba install -c colomoto -y -q maboss
          MaBoSS -h && echo "MaBoSS has been successfully installed."
          python -m pip install --upgrade pip
          pip install -r pip/requirements.txt
          pip install --use-pep517 -e . 
          python -c "import NORDic; print('NORDic has been successfully installed and importable in Python.')"
      - name: Test NI (CCHS)
        run: |
          cd tests/ && python -m tests_NI
      - name: Test SIM (CCHS) 
        shell: bash -l {0}
        run: |
          cd tests/ && python -m tests_sim